name: Run build linux

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      TRAVIS_BUILD_DIR: ${{ github.workspace }}
      TARGET: linux64
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          path: IFT-3100
          submodules: 'recursive'

      - name: Checkout openFrameworks
        uses: actions/checkout@v3
        with:
          repository: openframeworks/openFrameworks
          path: openFrameworks
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: 'recursive'

      - name: Checkout TheBoje/ofxImGui
        uses: actions/checkout@v3
        with:
          repository: TheBoje/ofxImGui
          path: openFrameworks/addons/ofxImGui
          ref: develop
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: 'recursive'


      - name: Checkout kylemcdonald/ofxCv
        uses: actions/checkout@v3
        with:
          repository: kylemcdonald/ofxCv
          path: openFrameworks/addons/ofxCv
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: 'recursive'

      - name: Install GLFW3
        run: |
          echo 'deb http://ppa.launchpad.net/keithw/glfw3/ubuntu trusty main' >> /etc/apt/sources.list
          sudo apt-get update -y
          sudo apt-get install libglfw3 -y
          sudo apt-get install libglfw3-dev -y

      - name: Download openFrameworks libs
        run: sudo openFrameworks/scripts/linux/download_libs.sh -a 64gcc6;

      - name: Install openFrameworks dependencies
        run: |
          export OF_ROOT=${{ github.workspace }}/openFrameworks
          sudo openFrameworks/scripts/ci/linux64/install.sh;

      - name: Build IFT-3100
        run: |
          ls
          cd IFT-3100
          make -j OF_ROOT=${{ github.workspace }}/openFrameworks