name: Run build linux

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          path: IFT-3100

      - name: Checkout openFrameworks
        uses: actions/checkout@v3
        with:
          repository: openframeworks/openFrameworks
          path: openFrameworks
          ref: stable
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: 'recursive'

      - name: Checkout TheBoje/ofxImGui
        uses: actions/checkout@v3
        with:
          repository: TheBoje/ofxImGui
          path: openFrameworks/addons/ofxImGui
          ref: develop
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout kylemcdonald/ofxCv
        uses: actions/checkout@v3
        with:
          repository: kylemcdonald/ofxCv
          path: openFrameworks/addons/ofxCv
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install openFrameworks dependencies
        run: sudo openFrameworks/scripts/linux/ubuntu/install_dependencies.sh -y

      - name: Build IFT-3100
        run: |
          ls
          cd IFT-3100
          make OF_ROOT=${{ github.workspace }}/openFrameworks